global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'faultline-orchestrator'
    static_configs:
      - targets: ['orchestrator:8080']

  - job_name: 'faultline-analytics'
    static_configs:
      - targets: ['analytics:8000']
